builds:
  - goos:
      - darwin
      - linux
      - windows

archives:
  -
    replacements:
      amd64: x86_64
      386: i386

    name_template: "{{ .Binary }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}"

    format: binary
